spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${db.url:jdbc:mariadb://localhost:3306/test0520}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${db.username:yong}
    password: ${db.password:hui3440}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: com.sling.test0520.config.MyMariaDBDialect
    show-sql: true
  thymeleaf:
    cache: false
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
gnmkoreaweb:
  files:
    image:
      path: /image
      max-size: 100MB
      exts: "*"
    attach:
      path: /attach
      max-size: 100MB
      exts: "*"
  upload:
    path: c:/devel/test0520/data/upload
server:
  port: 8008
  tomcat:
    max-http-form-post-size: 100MB